---
-
  hosts: agent3
  gather_facts: false
  remote_user: ubuntu
  become: true
  become_user: root
  become_method: sudo
  tasks: 
    - 
      name: Install Python2
      raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python-minimal)
    - 
      name: Fancy way of doing authorized_keys
      authorized_keys: user=root exclusive=no key=\"{{ lookup('file','~/.ssh/id_rsa.pub') }}\""
